### ISSUE TITLE
Guest and Host Story: Contact Information

### ISSUE THREAD

**Issue by vnbruno** [tylersuchan/symphoni#13]
As a guest or host I would like to be able to find a Contact Symphoni page to contact the creators if I have questions, or want to submit something.

**Comment by tylersuchan** [comment]
Acceptance Tests
1. Open the applications home page. This is done by opening the index.html. The initial page you see is the home page. Please scroll to the top of the page, using either the track-pad or a mouse.

2. After opening this page, you will find a "Contact Us" button. Click on that button, which will bring you to the "Contact Us" section.

3. Within that section will be information about the creators and information on how to contact them for any issues/questions.

**Comment by vnbruno** [comment]
Duplicate with another story, other story was written more clear.
