### ISSUE TITLE
Guest and Host Story

### ISSUE THREAD

**Issue by vnbruno** [tylersuchan/symphoni#19]
As a guest or host I would like the application to have a nice and clean user interface, so the application is a better experience when used.

**Comment by rossventresca** [comment]
Acceptance Test:
(1) UI contains start room and join room button
(2) UI contains sidebar or footer of privacy policy and contact information
(3) UI contains an about the application section
(4) Present to client with a prototype UI and get approval

**Comment by vnbruno** [comment]
This was a test issue, before we knew how to do the story's properly.
