### ISSUE TITLE
Host Story

### ISSUE THREAD

**Issue by corwynnielsen** [tylersuchan/symphoni#21]
As a host I would like there to be a clickable button on the home page to create a party.

**Comment by vnbruno** [comment]
Acceptance Tests:

1) Open the applications home page. This is done by opening the index.html. The initial page you see is the home page.
2) On the home page on the upper-mid-left side, there is a button that says "Start Party" click that button.
3) After clicking that button it will move to a page that will be asking you for "Party Name". Enter a name and hit the "Enter" button
4) This will conclude the "Start Party" acceptance test.
