### ISSUE TITLE
Guest Story

### ISSUE THREAD

**Issue by corwynnielsen** [tylersuchan/symphoni#22]
As a guest, I would like a clickable button on the homepage to join a party.

**Comment by vnbruno** [comment]
Acceptance Tests:

1)Open the applications home page. This is done by opening the index.html. The initial page you see is the home page.
2) On the home page on the upper-mid-right side, there is a button that says "Join Party" click that button.
3) After clicking that button it will move to a page that will be asking you for "Party Code". Enter the code and hit the "Enter" button
4) This will conclude the "Join Party" acceptance test.
