### ISSUE TITLE
Host/Guest Story

### ISSUE THREAD

**Issue by corwynnielsen** [tylersuchan/symphoni#41]
As a host or guest, I would like to see a section with the song queue

**Comment by vnbruno** [comment]
Acceptance Tests:

1) Open the applications home page. This is done by opening the index.html. The initial page you see is the home page. Please scroll to the top of the page, using either the track-pad or a mouse.
2) Then scroll down slowly until you see "Your Playlist" it will have a Title, Artist, Album.
3) You will see a song "4th Dimension" and "Nonstop"
4) This is the queue.

This will conclude the acceptance test.
