### ISSUE TITLE
Fill Out "Contact Us" section

### ISSUE THREAD

**Issue by tylersuchan** [tylersuchan/symphoni#54]
Fill out information required for "Contact Us" section, general information about the app, information on how to reach out to the creators, etc.

**Comment by tylersuchan** [comment]
Fill out designated field

**Comment by tylersuchan** [comment]
This task may shift gears into a combined information section or remain the same. Either way, Vinny is gonna handle it.

**Comment by vnbruno** [comment]
Acceptance Test:

Step 1: load up the home page
Step 2: scroll down to the bottom you should see a collapsible footer, it will have About Us, Contact Us, Privacy Policy
Step 3: hit the Contact Us, like just click on it
Step 4: it should open with all our emails
Step 5: read the emails
Step 6: this concludes the story, the goal is so people can contact us
