### ISSUE TITLE
Generate Priv Policy

### ISSUE THREAD

**Issue by vnbruno** [tylersuchan/symphoni#75]
Use an online generator to create a Priv Policy. When we are actually funded we can have a lawyer review it.

**Comment by ohadkatz** [comment]
Resorted to using https://www.spotify.com/us/legal/privacy-policy/ as our privacy policy.

Task Test:
Read the spotify policy and make sure that the link in the privacy policy is linked to that site.

**Comment by ohadkatz** [comment]
resorted to using https://www.spotify.com/us/legal/privacy-policy/ for our privacy policy

Task Test:
Make sure that our privacy policy is correctly linked to the spotify page.

**Comment by ohadkatz** [comment]
reverted to using spotify's privacy policy
Task Test:
Make sure privacy policy correctly links to spotify's page
